DeviceShop/Areas/Admin/Controllers/AssignController.cs
using DeviceShop.Areas.Admin.Models;
using DeviceShop.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeviceShop.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admin")]
    [Area("Admin")]
    public class AssignController : Controller
    {
        RoleManager<IdentityRole> _rm;
        UserManager<IdentityUser> _um;
        ApplicationDbContext _db;
        public AssignController(RoleManager<IdentityRole> rm, UserManager<IdentityUser> um, ApplicationDbContext db)
        {
            _rm = rm;
            _um = um;
            _db=db;
        }
        public IActionResult Index()
        {
            return View();
        }


        public ActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_db.ApplicationUsers.ToList(), "Id", "UserName");
            ViewData["RoleId"] = new SelectList(_rm.Roles.ToList(), "Name", "Name");

            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Create(UserRoleVM vM)
        {
            var user = _db.ApplicationUsers.FirstOrDefault(x => x.Id == vM.UserId);
            //var user = await _um.FindByIdAsync(id);
            var isExist = await _um.IsInRoleAsync(user,vM.RoleId);
            if (isExist==true)
            {
                ViewBag.msg = "This user already assigned";
                return View();
            }
            var role = await _um.AddToRoleAsync(user, vM.RoleId);
            if (role.Succeeded)
            {

                TempData["save"] = "User Role has been assigned ";
                return RedirectToAction(nameof(AssignUserRole));
            }
            return View();
        }




        public IActionResult AssignUserRole()
        {
            var result = from ur in _db.UserRoles
                         join r in _db.Roles on ur.RoleId equals r.Id
                         join u in _db.ApplicationUsers on ur.UserId equals u.Id
                         select new UserRoleMappingVM()
                         {
                             UserId=ur.UserId,
                             RoleId=ur.RoleId,
                             UserName=u.UserName,
                             RoleName=r.Name
                         };
            ViewBag.UserRole = result;
            return View();
            //return Json(new { data = ViewBag.UserRole });
        }

        


       
    }
}

DeviceShop/Areas/Admin/Controllers/ProductController.cs
using DeviceShop.Data;
using DeviceShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
//using System.Web.Mvc;

namespace DeviceShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class ProductController : Controller
    {
        private ApplicationDbContext _db;
        private IWebHostEnvironment _he;

        public ProductController(ApplicationDbContext db, IWebHostEnvironment he)
        {
            _db = db;
            _he = he;
        }
        public IActionResult Index()
        {

            return View();
        }
        public ActionResult Details(int id)
        {
            var product = _db.Products.Include(c => c.ProductType).Include(d => d.SpecialTag).FirstOrDefault(x => x.Id == id);
            return View(product);
        }

        //Create Get action Method

        public ActionResult Create()
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(),"Id","ProductsType");
            ViewData["tagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "TagName");
            return View();
        }


        public ActionResult GetAll()
        {
            List<Product> products = _db.Products.Include(c => c.ProductType).Include(d => d.SpecialTag).ToList< Product>();
            return Json(new { data = products });
        }

        //Edit Get action Method
        public ActionResult Edit(int id, IFormFile image)
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductsType");
            ViewData["tagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "TagName");
            var product = _db.Products.FirstOrDefault(x => x.Id == id);
            return View(product);
        }


        //Create Post action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Product product,IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    product.Image = "images/" + image.FileName;
                }
                else
                {
                    product.Image = "images/noimage.png";
                }

                _db.Products.Add(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                //TempData["save"] = "Saved Succeessfully";
            }
            return View(product);

        }


        //Edit Post action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id,Product product, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    product.Image = "images/" + image.FileName;
                }
                else
                {

                    //Product obj = _db.Products.Where(x => x.Id == id).FirstOrDefault<Product>();
                    //product.Image = obj.Image;
                }

                _db.Products.Update(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                //TempData["save"] = "Saved Succeessfully";
            }
            return View(product);
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {

            var product = _db.Products.Where(x => x.Id == id).FirstOrDefault<Product>();
            _db.Remove(product);
            _db.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully" });

        }
    }
}

DeviceShop/Areas/Admin/Controllers/RoleController.cs
using DeviceShop.Areas.Admin.Models;
using DeviceShop.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeviceShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _rm;
        ApplicationDbContext _db;
        public RoleController(RoleManager<IdentityRole> rm, ApplicationDbContext db)
        {
            _rm = rm;
            _db=db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            var role = _rm.Roles.ToList();
            ViewBag.Roles = role;
            return Json(new { data = ViewBag.Roles });
        }

        public IActionResult Create()
        {
            return View();
        }
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _rm.FindByIdAsync(id);
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole();
                role.Name = name;
                var isExist = await _rm.RoleExistsAsync(role.Name);
                if (isExist == true)
                {
                    ViewBag.mgs = "This Role Already Exist";
                    return View();
                }
                var result = await _rm.CreateAsync(role);
                if (result.Succeeded)
                {

                    TempData["save"] = "Role has been created Successfully";
                    return RedirectToAction(nameof(Index));
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, string name)
        {
            var role = await _rm.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = name;
            var isExist = await _rm.RoleExistsAsync(role.Name);
            if (isExist == true)
            {
                ViewBag.mgs = "This Role Already Exist";
                return View();
            }
            var result = await _rm.UpdateAsync(role);
            if (result.Succeeded)
            {

                TempData["edit"] = "Role has been updated Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        [HttpPost]
        public async Task<ActionResult>  Delete(string id)
        {
            var role = await _rm.FindByIdAsync(id);
            await _rm.DeleteAsync(role);
            return Json(new { success = true, message = "Deleted Successfully" });
        }

       
    }
}

DeviceShop/Areas/Customer/Controllers/UserController.cs
using DeviceShop.Data;
using DeviceShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeviceShop.Areas.Customer.Controllers
{
    

    [Area("Customer")]
    public class UserController : Controller
    {
        UserManager<IdentityUser> _userManager;
        ApplicationDbContext _db;
        public UserController(UserManager<IdentityUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult GetAll()
        {
            List<ApplicationUser> applicationUsers = _db.ApplicationUsers.ToList<ApplicationUser>();
            return Json(new { data = applicationUsers });
        }

        
        public IActionResult Create()
        {
            return View();
        }

        public async Task<ActionResult>  Edit(string id)
        {
            var user = await _db.ApplicationUsers.FindAsync(id);
            return View(user);
        }


       
        [HttpPost]
        public async Task<IActionResult> Create(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                var result = await _userManager.CreateAsync(user, user.PasswordHash);
                if (result.Succeeded)
                {
                    var roleSave = await _userManager.AddToRoleAsync(user, "Customer");
                    TempData["save"] = "User has been created Successfully";
                    return RedirectToAction(nameof(Index));
                }
              
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }  
            }
            return View(user);
        }

        [Authorize(Roles ="Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                var userInfo = _db.ApplicationUsers.FirstOrDefault(x => x.Id == user.Id);
                userInfo.FirstName = user.FirstName;
                userInfo.LastName = user.LastName;
                userInfo.UserName = user.UserName;
                var result = await _userManager.UpdateAsync(userInfo);
                if (result.Succeeded)
                {
                    TempData["edit"] = "User has been Updated";
                    return RedirectToAction(nameof(Index));
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Delete(string id)
        {   
            var user = _db.ApplicationUsers.Where(x => x.Id == id).FirstOrDefault<ApplicationUser>();
            _db.Remove(user);
            _db.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully" });   
        }


        //For Lockout & Lockend
        //user.LockoutEnd = DateTime.Now.AddMonths(2);
        //user.LockoutEnd = DateTime.Now.AddDays(-1);
    }
}

DeviceShop/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductType" class="btn btn-success"></a>
        <a asp-action="Details" asp-controller="ProductType" class="btn btn-primary"></a>
        <a asp-action="Delete" asp-controller="ProductType" class="btn btn-danger"></a>
    </div>
</td>

DeviceShop/Views/Shared/_Layout.cshtml
@using DeviceShop.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{ 
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");

    int count = 0;
    List<Product> products = HttpContextAccessor.HttpContext.Session.Get<List<Product>>("products");
    if (products == null)
    {
        products = new List<Product>();
    }
    count = products.Count();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title >@ViewData["Title"] - DeviceShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    
    <style>
        .error{
            color:red;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:palevioletred" >DeviceShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductType" asp-action="Index">Product Type</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">SpecialTag</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductOrder" asp-action="Index">Order</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User
                                </a>
                                <div class="dropdown-menu badge-dark" aria-labelledby="navbarDropdown">
                                    <a class="nav-link btn-outline-secondary" asp-area="Customer" asp-controller="User" asp-action="Index" style="color:white">View Users</a>
                                    <a class="nav-link btn-outline-secondary" asp-area="Admin" asp-controller="Role" asp-action="Index" style="color:white">View Roles</a>
                                    <a class="nav-link btn-outline-secondary" asp-area="Admin" asp-controller="Assign" asp-action="AssignUserRole" style="color:white">View User's Role</a>
                                    <a class="nav-link btn-outline-secondary" asp-area="Customer" asp-controller="User" asp-action="Create" style="color:white">Create Users</a>
                                    <a class="nav-link btn-outline-secondary" asp-area="Admin" asp-controller="Role" asp-action="Create" style="color:white">Create Roles</a>
                                    <a class="nav-link btn-outline-secondary" asp-area="Admin" asp-controller="Assign" asp-action="Create" style="color:white">Assign UserRole</a>

                                </div>
                            </li>
                        }
                        @if (userRole == "Admin" || userRole == "Customer")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart"><i class="fas fa-cart-plus"></i><label>&nbsp;(@count)</label> </a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DeviceShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>